version: "3.7"

services:
  server:
    image: adguard/adguardhome:v0.107.46
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/work:/opt/adguardhome/work
      - ${APP_DATA_DIR}/data/conf:/opt/adguardhome/conf
    network_mode: host
    ports:
      # plain DNS
      - 53:53/tcp
      - 53:53/udp
      # DHCP Server
      # - 67:67/udp
      # - 68:68/tcp
      # - 68:68/udp
      # HTTP
      - 8000:80/tcp
      - 8000:80/udp
      # Setup
      - 3000:3000/tcp
      - 3000:3000/udp
      # DNS-over-HTTPS
      # - 443:443/tcp
      # - 443:443/udp
      # DNS-over-TLS
      - 853:853/tcp
      # DNS-over-QUIC
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp

#networks:
  #adguard-home-network:
    #driver: bridge