version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: speedtest-tracker-2_server_1
      APP_PORT: 80

  server:
    image: "linuxserver/speedtest-tracker:1.6.0"
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=umbrel
      - DB_PASSWORD=umbrel
      - TZ=Etc/UTC
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${APP_DATA_DIR}/config:/config"
      - "${APP_DATA_DIR}/web:/etc/ssl/web"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mariadb:10
    restart: always
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=umbrel
      - MARIADB_PASSWORD=umbrel
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - "${APP_DATA_DIR}/mariadb:/var/lib/mysql"