version: "3.7"

services:
  unbound:
    container_name: unbound
    image: "mvance/unbound:latest"
    expose:
      - "53"
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    volumes:
      - ${APP_DATA_DIR}/data/config/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf
      - ${APP_DATA_DIR}/data/config/a-records.conf:/opt/unbound/etc/unbound/a-records.conf
    network_mode: host
    restart: always