version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ozturk-umbrel-easypanel_server_1
      APP_PORT: 3000

  server:
    # Service for running Chromium browser in a container
    image: easypanel/easypanel:latest

    # Set environment variables for the container
    environment:
      - PUID=1000 # Set the user ID for the container process (optional)
      - PGID=1000 # Set the group ID for the container process (optional)
      - TZ=Etc/UTC # Set the timezone inside the container to UTC (optional)

    # Mount volumes from the host into the container
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      # Map the host directory /data/chromium/config to the container's /config directory
      # This allows the container to read/write configuration files to the specified host directory

    # Define the restart policy for the container
    restart: unless-stopped
    # This means the container will automatically restart unless explicitly stopped by the user or Docker itself