version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ozturk-umbrel-easypanel_server_1
      APP_PORT: 3000

  server:
    image: easypanel/easypanel:canary

    # Set environment variables for the container
    environment:
      - PUID=1000 # Set the user ID for the container process (optional)
      - PGID=1000 # Set the group ID for the container process (optional)
      - TZ=Etc/UTC # Set the timezone inside the container to UTC (optional)
      - RELEASE_TAG=canary

    # Mount volumes from the host into the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/etc/easypanel:/etc/easypanel

    # Define the restart policy for the container
    restart: unless-stopped
    # This means the container will automatically restart unless explicitly stopped by the user or Docker itself