version: "3.7"

services:
  server:
    image: jlesage/jdownloader-2:v24.01.1
    restart: on-failure
    stop_grace_period: 1m
    #network_mode: host
    #privileged: true
    # Define security options for the container
    security_opt:
    # For Docker Engine only, many modern gui apps need this to function on older hosts as syscalls are unknown to Docker. Chromium runs in no-sandbox test mode without it.
      - seccomp:unconfined # Enable unconfined seccomp mode for this container (optional)
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - JDOWNLOADER_HEADLESS=
      - MYJDOWNLOADER_DEVICE_NAME=
      - MYJDOWNLOADER_EMAIL=
      - MYJDOWNLOADER_PASSWORD=
      - TZ=Europe/Istanbul
    ports:
      - 5800:5800/tcp
      - 5900:5900/tcp
      - 3129:3129/tcp
    # Set the size of the container's shared memory segment
    shm_size: "512mb" # Allocate 1 GB of shared memory (RAM) for this container