version: "3.7"

services:
  server:
    image: ubuntu/squid:6.1-23.10_beta
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data/squid.conf:/etc/squid/squid.conf
      - ${APP_DATA_DIR}/data/passwords:/etc/squid/passwords