version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ozturk-flaresolverr_server_1
      APP_PORT: 8191
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.16
    restart: on-failure
    stop_grace_period: 1m
    environment:
      # - PORT=4000
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/London