version: "3.7"

services:
  server:
      image: ghcr.io/mhsanaei/3x-ui:latest
      container_name: 3x-ui
      hostname: "3x-ui"
      volumes:
        - ${APP_DATA_DIR}/data:/etc/x-ui
        - ${APP_DATA_DIR}/data/acme:/root/.acme.sh
      environment:
        XRAY_VMESS_AEAD_FORCED: "false"
        X_UI_ENABLE_FAIL2BAN: "true"
      ports:
      - 2053:2053/tcp
      - 8443:8443/tcp
      - 443:443/tcp
      tty: true
      network_mode: host
      restart: always