version: "3.7"

services:
  server:
      image: ghcr.io/mhsanaei/3x-ui:latest
      container_name: 3x-ui
      hostname: localhost
      volumes:
        - ${APP_DATA_DIR}/data/3x-ui/data/db/:/etc/x-ui/
        - ${APP_DATA_DIR}/data/3x-ui/data/cert/:/root/cert/
      environment:
        XRAY_VMESS_AEAD_FORCED: "false"
        X_UI_ENABLE_FAIL2BAN: "true"
      ports:
      - 2053:2053/tcp
      tty: true
      network_mode: host
      restart: always